/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home1;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import project.Project_Home;
import stock1.stock_main;

/**
 *
 * @author YAYO
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Home() {
        this.setUndecorated(false);
        this.setAlwaysOnTop(false);
        this.setResizable(true);
        this.setVisible(true);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewaccBtn = new javax.swing.JButton();
        StockBtn1 = new javax.swing.JButton();
        projectbtn1 = new javax.swing.JButton();
        reg_btn = new javax.swing.JButton();
        reportBtn3 = new javax.swing.JButton();
        payrollBtn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        NewaccBtn.setBackground(new java.awt.Color(0, 102, 255));
        NewaccBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NewaccBtn.setForeground(new java.awt.Color(255, 255, 255));
        NewaccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/NewACC.png"))); // NOI18N
        NewaccBtn.setText("CREATE NEW ACCOUNT");
        NewaccBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NewaccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewaccBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewaccBtnMouseExited(evt);
            }
        });
        NewaccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewaccBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NewaccBtn);
        NewaccBtn.setBounds(180, 160, 220, 59);

        StockBtn1.setBackground(new java.awt.Color(0, 102, 255));
        StockBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StockBtn1.setForeground(new java.awt.Color(255, 255, 255));
        StockBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/stockico.png"))); // NOI18N
        StockBtn1.setText("STOCK");
        StockBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StockBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockBtn1MouseExited(evt);
            }
        });
        StockBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(StockBtn1);
        StockBtn1.setBounds(180, 330, 220, 59);

        projectbtn1.setBackground(new java.awt.Color(0, 102, 255));
        projectbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        projectbtn1.setForeground(new java.awt.Color(255, 255, 255));
        projectbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Projectico2.png"))); // NOI18N
        projectbtn1.setText("PROJECT");
        projectbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        projectbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectbtn1MouseExited(evt);
            }
        });
        projectbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(projectbtn1);
        projectbtn1.setBounds(180, 250, 220, 59);

        reg_btn.setBackground(new java.awt.Color(0, 102, 255));
        reg_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reg_btn.setForeground(new java.awt.Color(255, 255, 255));
        reg_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/RegisterIcon.png"))); // NOI18N
        reg_btn.setText("REGISTRATION");
        reg_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_btnMouseExited(evt);
            }
        });
        reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reg_btn);
        reg_btn.setBounds(490, 160, 220, 59);

        reportBtn3.setBackground(new java.awt.Color(0, 102, 255));
        reportBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportBtn3.setForeground(new java.awt.Color(255, 255, 255));
        reportBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ReportIcon.png"))); // NOI18N
        reportBtn3.setText("REPORTS");
        reportBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportBtn3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                reportBtn3StateChanged(evt);
            }
        });
        reportBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportBtn3MouseExited(evt);
            }
        });
        reportBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtn3ActionPerformed(evt);
            }
        });
        reportBtn3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                reportBtn3PropertyChange(evt);
            }
        });
        getContentPane().add(reportBtn3);
        reportBtn3.setBounds(490, 330, 220, 59);

        payrollBtn3.setBackground(new java.awt.Color(0, 102, 255));
        payrollBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        payrollBtn3.setForeground(new java.awt.Color(255, 255, 255));
        payrollBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/payroll.png"))); // NOI18N
        payrollBtn3.setText("PAYROLL");
        payrollBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        payrollBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payrollBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payrollBtn3MouseExited(evt);
            }
        });
        payrollBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(payrollBtn3);
        payrollBtn3.setBounds(490, 250, 220, 59);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewaccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewaccBtnActionPerformed

    }//GEN-LAST:event_NewaccBtnActionPerformed

    private void projectbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectbtn1ActionPerformed
        project.Project_Home a = new Project_Home();
        a.setVisible(true);
        a.setDefaultCloseOperation(Project_Home.DISPOSE_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_projectbtn1ActionPerformed

    private void reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_btnActionPerformed

    private void reportBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportBtn3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()| JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void StockBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockBtn1ActionPerformed
        stock1.stock_main s = new stock_main();
        s.setVisible(true);
        s.setDefaultCloseOperation(Project_Home.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_StockBtn1ActionPerformed

    private void payrollBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollBtn3ActionPerformed
       
    }//GEN-LAST:event_payrollBtn3ActionPerformed

    private void NewaccBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewaccBtnMouseEntered
        NewaccBtn.setForeground(Color.yellow);
    }//GEN-LAST:event_NewaccBtnMouseEntered

    private void NewaccBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewaccBtnMouseExited
        NewaccBtn.setForeground(Color.white);
    }//GEN-LAST:event_NewaccBtnMouseExited

    private void projectbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectbtn1MouseEntered
        projectbtn1.setForeground(Color.yellow);
    }//GEN-LAST:event_projectbtn1MouseEntered

    private void projectbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectbtn1MouseExited
        projectbtn1.setForeground(Color.white);
    }//GEN-LAST:event_projectbtn1MouseExited

    private void StockBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBtn1MouseEntered
        StockBtn1.setForeground(Color.yellow);
    }//GEN-LAST:event_StockBtn1MouseEntered

    private void StockBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBtn1MouseExited
        StockBtn1.setForeground(Color.white);
    }//GEN-LAST:event_StockBtn1MouseExited

    private void reg_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseEntered
        reg_btn.setForeground(Color.yellow);
    }//GEN-LAST:event_reg_btnMouseEntered

    private void reg_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseExited
        reg_btn.setForeground(Color.white);
    }//GEN-LAST:event_reg_btnMouseExited

    private void payrollBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollBtn3MouseEntered
        payrollBtn3.setForeground(Color.yellow);
    }//GEN-LAST:event_payrollBtn3MouseEntered

    private void payrollBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollBtn3MouseExited
       payrollBtn3.setForeground(Color.white);
    }//GEN-LAST:event_payrollBtn3MouseExited

    private void reportBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtn3MouseEntered
        reportBtn3.setForeground(Color.yellow);
    }//GEN-LAST:event_reportBtn3MouseEntered

    private void reportBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtn3MouseExited
        reportBtn3.setForeground(Color.white);
    }//GEN-LAST:event_reportBtn3MouseExited

    private void reportBtn3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_reportBtn3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_reportBtn3PropertyChange

    private void reportBtn3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_reportBtn3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_reportBtn3StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewaccBtn;
    private javax.swing.JButton StockBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton payrollBtn3;
    private javax.swing.JButton projectbtn1;
    private javax.swing.JButton reg_btn;
    private javax.swing.JButton reportBtn3;
    // End of variables declaration//GEN-END:variables
}
